#!/bin/bash
# ─── Deploy to HuggingFace Spaces ────────────────────────────────────────────
# Prerequisites: pip install huggingface_hub

echo "🤗 Deploying to HuggingFace Spaces"
echo "==================================="
echo ""
echo "STEP 1: Login to HuggingFace"
echo "   huggingface-cli login"
echo ""
echo "STEP 2: Build the React frontend first"
echo "   cd frontend && npm run build && cd .."
echo ""
echo "STEP 3: Create a new Space on https://huggingface.co/new-space"
echo "   - SDK: Docker"
echo "   - Name: energy-consumption-forecast"
echo ""
echo "STEP 4: Push to the Space"
echo "   git init"
echo "   git remote add hf https://huggingface.co/spaces/YOUR_USERNAME/energy-consumption-forecast"
echo "   git add ."
echo "   git commit -m 'Initial deployment'"
echo "   git push hf main"
echo ""
echo "STEP 5: Your app will be live at:"
echo "   https://huggingface.co/spaces/YOUR_USERNAME/energy-consumption-forecast"
echo ""
echo "NOTE: First build on HF may take 5-10 minutes (Docker build)."
echo "      Free tier has CPU-only inference — model runs fast enough."
